const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();tg.setHeaderColor('#071018');tg.setBackgroundColor('#071018')}
const PRODUCTS=[
{id:1,name:"PLA — Белый",type:"PLA",price:130000,weight:"1 кг",diameter:"1.75 мм",color:"Белый",emoji:"⚪"},
{id:2,name:"PLA — Чёрный",type:"PLA",price:130000,weight:"1 кг",diameter:"1.75 мм",color:"Чёрный",emoji:"⚫"},
{id:3,name:"PETG — Чёрный",type:"PETG",price:150000,weight:"1 кг",diameter:"1.75 мм",color:"Чёрный",emoji:"⚫"},
{id:4,name:"PETG — Синий",type:"PETG",price:150000,weight:"1 кг",diameter:"1.75 мм",color:"Синий",emoji:"🔵"},
{id:5,name:"TPU — Синий",type:"TPU",price:180000,weight:"1 кг",diameter:"1.75 мм",color:"Синий",emoji:"🔵"},
{id:6,name:"ABS — Чёрный",type:"ABS",price:140000,weight:"1 кг",diameter:"1.75 мм",color:"Чёрный",emoji:"⚫"}
];
let cart=JSON.parse(localStorage.getItem("layerone_cart")||"[]"), currentFilter="all", currentProduct=null, geo=null;
const money=n=>n.toLocaleString("ru-RU")+" сум";
function save(){localStorage.setItem("layerone_cart",JSON.stringify(cart));updateBadge()}
function updateBadge(){document.getElementById("cartBadge").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function showScreen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));if(id==="catalog")renderProducts();if(id==="cart")renderCart();if(id==="home")renderCats();window.scrollTo(0,0)}
function renderCats(){document.getElementById("categories").innerHTML=[["PLA","⚪"],["PETG","🔵"],["ABS","⚫"],["TPU","🟣"]].map(([x,e])=>`<button class="cat" onclick="setFilter('${x}')"><span class="emoji">${e}</span>${x}</button>`).join("")}
function setFilter(f){currentFilter=f;showScreen("catalog");document.querySelectorAll(".filter").forEach(b=>b.classList.toggle("active",b.dataset.filter===f))}
function renderProducts(){const q=(document.getElementById("search")?.value||"").toLowerCase();let arr=PRODUCTS.filter(p=>(currentFilter==="all"||p.type===currentFilter)&&(`${p.name} ${p.type}`.toLowerCase().includes(q)));document.getElementById("products").innerHTML=arr.map(p=>`<div class="product" onclick="openProduct(${p.id})"><div class="product-img">${p.emoji}</div><div class="product-info"><h3>${p.name}</h3><div class="meta">${p.diameter} • ${p.weight}</div><div class="price">${money(p.price)}</div></div><button class="add" onclick="event.stopPropagation();add(${p.id})">+</button></div>`).join("")||"<p class='meta'>Ничего не найдено.</p>"}
function openProduct(id){currentProduct=PRODUCTS.find(p=>p.id===id);const p=currentProduct;document.getElementById("productDetail").innerHTML=`<div class="product-detail"><div class="big-img">${p.emoji}</div><div class="detail"><h1>${p.name}</h1><div class="price" style="font-size:22px">${money(p.price)}</div><div class="specs"><div class="spec"><span>Материал</span><b>${p.type}</b></div><div class="spec"><span>Диаметр</span><b>${p.diameter}</b></div><div class="spec"><span>Вес</span><b>${p.weight}</b></div><div class="spec"><span>Цвет</span><b>${p.color}</b></div></div><p class="meta" style="margin-top:14px">Качественный филамент для стабильной 3D-печати. Характеристики можно изменить в каталоге магазина.</p><button class="primary full" onclick="add(${p.id});showScreen('cart')">Добавить в корзину</button></div></div>`;showScreen("product")}
function add(id){let x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id,qty:1});save();if(tg)tg.HapticFeedback?.impactOccurred("light")}
function dec(id){let x=cart.find(x=>x.id===id);if(!x)return;x.qty--;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);save();renderCart()}
function clearCart(){cart=[];save();renderCart()}
function renderCart(){const el=document.getElementById("cartItems");if(!cart.length){el.innerHTML="<div class='total-box'>Корзина пока пуста.</div>";document.getElementById("cartTotal").innerHTML="";return}el.innerHTML=cart.map(x=>{let p=PRODUCTS.find(p=>p.id===x.id);return`<div class="cart-item"><div class="product-img">${p.emoji}</div><div style="flex:1"><b>${p.name}</b><div class="meta">${p.weight} • ${money(p.price)}</div><div class="qty"><button onclick="dec(${p.id})">−</button><b>${x.qty}</b><button onclick="add(${p.id});renderCart()">+</button></div></div><b>${money(p.price*x.qty)}</b></div>`}).join("");let sum=cart.reduce((s,x)=>s+PRODUCTS.find(p=>p.id===x.id).price*x.qty,0);document.getElementById("cartTotal").innerHTML=`<div class="total-row"><span>Товары</span><b>${money(sum)}</b></div><div class="total-row"><span>Доставка</span><span>Оплачивается при получении</span></div><div class="total-row big"><span>Итого</span><span>${money(sum)}</span></div>`}
function showCheckout(){if(!cart.length)return;let sum=cart.reduce((s,x)=>s+PRODUCTS.find(p=>p.id===x.id).price*x.qty,0);document.getElementById("checkoutTotal").innerHTML=`<div class="total-row big"><span>К оплате за товары</span><span>${money(sum)}</span></div><div class="meta">Доставка оплачивается отдельно при получении.</div>`;showScreen("checkout")}
function requestLocation(){if(!tg?.requestLocation){alert("Откройте магазин внутри Telegram, чтобы использовать геолокацию.");return}tg.requestLocation((ok)=>{if(ok&&tg.initDataUnsafe?.location){geo=tg.initDataUnsafe.location;document.getElementById("address").value=`Геолокация: ${geo.latitude}, ${geo.longitude}`}})}
async function submitOrder(){let name=document.getElementById("name").value.trim(),phone=document.getElementById("phone").value.trim(),address=document.getElementById("address").value.trim(),comment=document.getElementById("comment").value.trim();if(!name||!phone||!address){alert("Заполните имя, телефон и адрес доставки.");return}let items=cart.map(x=>{let p=PRODUCTS.find(p=>p.id===x.id);return{name:p.name,qty:x.qty,price:p.price}}),sum=items.reduce((s,x)=>s+x.price*x.qty,0);let order={orderId:"L1-"+Date.now().toString().slice(-6),user:tg?.initDataUnsafe?.user||null,name,phone,address,comment,items,total:sum,delivery:"Оплачивается покупателем при получении",createdAt:new Date().toISOString()};const url=localStorage.getItem("layerone_backend_url");if(url){try{await fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(order)})}catch(e){console.log(e)}}else{console.log("ORDER",order)}cart=[];save();document.getElementById("successText").textContent=`Ваш заказ ${order.orderId} принят. Мы свяжемся с вами для подтверждения.`;showScreen("success");if(tg)tg.HapticFeedback?.notificationOccurred("success")}
document.getElementById("search")?.addEventListener("input",renderProducts);document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{currentFilter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderProducts()}));document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.screen)));document.getElementById("cartTop").onclick=()=>showScreen("cart");renderCats();renderProducts();updateBadge();